apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcart-web
  namespace: quickcart

spec:

  replicas: 2

  selector:
    matchLabels:
      app: quickcart-web

  template:

    metadata:
      labels:
        app: quickcart-web

    spec:

      containers:

        - name: web

          image: 523859314235.dkr.ecr.ap-south-1.amazonaws.com/quickcart/web:latest

          imagePullPolicy: Always

          ports:

            - containerPort: 80
              name: http

          resources:

            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:

            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:

            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 30
            periodSeconds: 20