name: QuickCart CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "523859314235"

  ECR_API: quickcart/api
  ECR_WEB: quickcart/web

  EKS_CLUSTER: quickcart-eks
  K8S_NAMESPACE: quickcart

  AWS_ROLE_ARN: arn:aws:iam::523859314235:role/ZeptoGitHubActionsRole

jobs:

  # ============================================================
  # CI - TEST
  # ============================================================

  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- Python API ----------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install API dependencies
        working-directory: services/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check API
        working-directory: services/api
        env:
          DATABASE_URL: postgresql://quickcart:quickcart123@localhost:5432/quickcart
          REDIS_URL: redis://localhost:6379/0
        run: |
          python -c "from app.main import app; print(app.title)"

      # ---------------- Frontend ----------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: services/web/package-lock.json

      - name: Install Web dependencies
        working-directory: services/web
        run: npm ci

      - name: Build Web application
        working-directory: services/web
        run: npm run build


  # ============================================================
  # BUILD AND PUSH
  # ============================================================

  build-and-push:
    name: Build and Push Images
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- AWS OIDC ----------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523859314235:role/ZeptoGitHubActionsRole
          aws-region: ap-south-1

      # ---------------- Verify AWS ----------------

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # ---------------- ECR Login ----------------

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- Image Variables ----------------

      - name: Set image variables
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "API_IMAGE=$REGISTRY/${{ env.ECR_API }}:$IMAGE_TAG" >> "$GITHUB_ENV"
          echo "WEB_IMAGE=$REGISTRY/${{ env.ECR_WEB }}:$IMAGE_TAG" >> "$GITHUB_ENV"

      # ---------------- Build API ----------------

      - name: Build API image
        run: |
          docker build \
            -t "$API_IMAGE" \
            ./services/api

      # ---------------- Scan API ----------------
      - name: Scan API image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.API_IMAGE }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          svuln-type: "os,library"

      # ---------------- Push API ----------------

      - name: Push API image
        run: |
          docker push "$API_IMAGE"

      # ---------------- API Latest ----------------

      - name: Push API latest
        run: |
          API_LATEST="${API_IMAGE%:*}:latest"
          docker tag "$API_IMAGE" "$API_LATEST"
          docker push "$API_LATEST"

      # ---------------- Build Web ----------------

      - name: Build Web image
        run: |
          docker build \
            -t "$WEB_IMAGE" \
            ./services/web

      # ---------------- Scan Web ----------------

      - name: Scan Web image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.WEB_IMAGE }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          vuln-type: "os,library"

      # ---------------- Push Web ----------------

      - name: Push Web image
        run: |
          docker push "$WEB_IMAGE"

      # ---------------- Web Latest ----------------

      - name: Push Web latest
        run: |
          WEB_LATEST="${WEB_IMAGE%:*}:latest"
          docker tag "$WEB_IMAGE" "$WEB_LATEST"
          docker push "$WEB_LATEST"


  # ============================================================
  # CD - DEPLOY TO EKS
  # ============================================================

  deploy:
    name: Deploy to EKS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- AWS OIDC ----------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523859314235:role/ZeptoGitHubActionsRole
          aws-region: ap-south-1

      # ---------------- Verify AWS ----------------

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # ---------------- Setup kubectl ----------------

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # ---------------- Connect to EKS ----------------

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$EKS_CLUSTER"

      # ---------------- Verify Cluster ----------------

      - name: Verify EKS connection
        run: |
          kubectl get nodes

      # ---------------- Deploy Infrastructure ----------------

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -k k8s/

      # ---------------- Set Image Variables ----------------

      - name: Set deployment image variables
        run: |
          REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

          echo "API_IMAGE=$REGISTRY/${ECR_API}:${GITHUB_SHA}" >> "$GITHUB_ENV"
          echo "WEB_IMAGE=$REGISTRY/${ECR_WEB}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      # ---------------- Update API ----------------

      - name: Update API deployment
        run: |
          kubectl set image \
            deployment/quickcart-api \
            api="$API_IMAGE" \
            -n "$K8S_NAMESPACE"

      # ---------------- Update Web ----------------

      - name: Update Web deployment
        run: |
          kubectl set image \
            deployment/quickcart-web \
            web="$WEB_IMAGE" \
            -n "$K8S_NAMESPACE"

      # ---------------- Wait for API ----------------

      - name: Wait for API
        run: |
          kubectl rollout status \
            deployment/quickcart-api \
            -n "$K8S_NAMESPACE" \
            --timeout=5m

      # ---------------- Wait for Web ----------------

      - name: Wait for Web
        run: |
          kubectl rollout status \
            deployment/quickcart-web \
            -n "$K8S_NAMESPACE" \
            --timeout=5m

      # ---------------- Final Status ----------------

      - name: Show deployment status
        run: |
          echo "========== DEPLOYMENTS =========="
          kubectl get deployments -n "$K8S_NAMESPACE"

          echo "========== PODS =========="
          kubectl get pods -n "$K8S_NAMESPACE"

          echo "========== SERVICES =========="
          kubectl get services -n "$K8S_NAMESPACE"